spring:
  application:
    name: analytics-backend
  profiles:
    active: dev
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/analytics
    username: analytics
    password: analytics
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics
    username: analytics
    password: analytics
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/analytics
    user: analytics
    password: analytics
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

security:
  jwt:
    issuer: pocm-analytics
    audience: pocm-services
    secret-base64: ${JWT_SECRET_BASE64:changeme}
    expiration-seconds: 3600
  api-keys:
    - dev-key-1

rate-limit:
  enabled: true
  window-seconds: 60
  max-requests: 100

cache:
  ttl-seconds: 60


kafka:
  topic-prefix: pocm.analytics

clickhouse:
  url: jdbc:clickhouse://localhost:8123/analytics
  username: default
  password: ""

